@startuml

skinparam StateBackgroundColor #FDFDFD
skinparam StateBorderColor #333333
skinparam DefaultTextAlignment center
skinparam ArrowColor #333333

[*] --> سبد_خرید

state سبد_خرید {

    [*] --> در_حال_ویرایش

    در_حال_ویرایش : افزودن کالا
    در_حال_ویرایش : حذف کالا
    در_حال_ویرایش : تغییر تعداد اقلام

    در_حال_ویرایش --> در_حال_ویرایش : ویرایش سبد / بروزرسانی مبلغ

}

سبد_خرید --> ثبت_شده :
تایید سفارش [سبد معتبر] / ثبت سفارش

state ثبت_شده {

    [*] --> در_انتظار_بررسی_موجودی

    state بررسی_موجودی <<choice>>

    در_انتظار_بررسی_موجودی --> بررسی_موجودی :
    بررسی موجودی / ارسال درخواست به انبار

    بررسی_موجودی --> در_انتظار_پرداخت :
    [موجودی کافی] / رزرو کالا

    بررسی_موجودی --> لغو_شده :
    [موجودی ناکافی] / ثبت کسری موجودی

    در_انتظار_پرداخت --> تایید_شده :
    پرداخت موفق [مبلغ کامل] / ثبت تراکنش پرداخت

    در_انتظار_پرداخت --> در_انتظار_پرداخت :
    پرداخت ناموفق / درخواست تلاش مجدد

    در_انتظار_پرداخت --> لغو_شده :
    انقضای مهلت پرداخت / لغو سفارش

}

state تایید_شده {

    [*] --> در_حال_آماده_سازی

    در_حال_آماده_سازی : جمع‌آوری کالا
    در_حال_آماده_سازی : بسته‌بندی سفارش
    در_حال_آماده_سازی : کنترل نهایی

    در_حال_آماده_سازی --> آماده_ارسال :
    آماده‌سازی کامل [سفارش تایید شده] / صدور بارنامه

}

state آماده_ارسال {

    [*] --> در_انتظار_تحویل_به_ناوگان

    در_انتظار_تحویل_به_ناوگان :
    انتظار برای تحویل به پیک

    در_انتظار_تحویل_به_ناوگان --> در_حال_ارسال :
    تحویل به ناوگان / ثبت اطلاعات ارسال

}

state در_حال_ارسال {

    [*] --> ارسال_شده

    ارسال_شده : انتقال سفارش به مقصد

    ارسال_شده --> تحویل_شده :
    تحویل موفق / ثبت تایید دریافت

    ارسال_شده --> مرجوع_شده :
    عدم پذیرش [مشتری] / ثبت درخواست مرجوعی

    ارسال_شده --> مرجوع_شده :
    آسیب‌دیدگی [در حمل] / ثبت گزارش خسارت

}

state تحویل_شده {

    [*] --> تکمیل_شده

    تکمیل_شده :
    ثبت نهایی تحویل سفارش

    تکمیل_شده :
    بروزرسانی موجودی و سوابق سفارش

}

state لغو_شده {

    [*] --> لغو_نهایی

    لغو_نهایی :
    ثبت علت لغو

    لغو_نهایی :
    آزادسازی رزرو کالا

    لغو_نهایی :
    بازگشت وجه در صورت نیاز

}

state مرجوع_شده {

    [*] --> در_حال_بررسی_مرجوعی

    در_حال_بررسی_مرجوعی :
    دریافت و بررسی کالای مرجوعی

    در_حال_بررسی_مرجوعی --> تایید_مرجوعی :
    بررسی کالا [شرایط مرجوعی برقرار] / تایید مرجوعی

    در_حال_بررسی_مرجوعی --> رد_مرجوعی :
    بررسی کالا [شرایط مرجوعی برقرار نیست] / رد درخواست

    تایید_مرجوعی --> بازگشت_وجه :
    تایید مرجوعی / شروع بازپرداخت

    بازگشت_وجه :
    بازپرداخت مبلغ سفارش

    بازگشت_وجه --> مرجوعی_تکمیل_شده :
    پرداخت موفق / ثبت بازپرداخت

    رد_مرجوعی --> پایان_مرجوعی :
    رد درخواست / ثبت نتیجه بررسی

}

تکمیل_شده --> [*]
لغو_نهایی --> [*]
مرجوعی_تکمیل_شده --> [*]
پایان_مرجوعی --> [*]

@enduml
